trigger: none

pool:
  vmImage: windows-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pyinstaller --onedir VGEM.py --icon Image\VitroLogo.ico --add-data "Image\*;."
  displayName: 'pyinstaller'

- task: CopyFiles@2
  inputs:
    contents: './dist/**'
    targetFolder: 'D:\a\1\s\dist\'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.Repository.LocalPath)
    artifactName: MyBuildOutputs
